const CHARACTERS = {
    FORWARD_SLASH: '/',
    WHITESPACE: ' ',
    COLON: ':',
    ZERO: '0',
    EQUALS: '=',
    AMPERSAND: '&',
    QUESTION_MARK: '?'
};
export const {FORWARD_SLASH, WHITESPACE, COLON, ZERO, EQUALS, AMPERSAND, QUESTION_MARK} = CHARACTERS;
export default CHARACTERS;
