export default {
    UPPERCASE: 'UPPERCASE',
    LOWERCASE: 'LOWERCASE',
    INTEGER: 'INTEGER',
    WHITESPACE: 'WHITESPACE',
    WORD: 'WORD',
    BOUNDARY: 'BOUNDARY',
    DIGIT: 'DIGIT',
    NOT_WHITESPACE: 'NOT_WHITESPACE',
    NOT_WORD: 'NOT_WORD',
    NOT_DIGIT: 'NOT_DIGIT',
    NOT_BOUNDARY: 'NOT_BOUNDARY'
};
