const PATTERNS = {
    UPPERCASE: 'UPPERCASE',
    LOWERCASE: 'LOWERCASE',
    INTEGER: 'INTEGER',
    WHITESPACE: 'WHITESPACE',
    WORD: 'WORD',
    BOUNDARY: 'BOUNDARY',
    DIGIT: 'DIGIT',
    NOT_WHITESPACE: 'NOT_WHITESPACE',
    NOT_WORD: 'NOT_WORD',
    NOT_DIGIT: 'NOT_DIGIT',
    NOT_BOUNDARY: 'NOT_BOUNDARY',
    TELEPHONE_MASK: 'TELEPHONE_MASK',
    EXTENSION_MASK: 'EXTENSION_MASK'
};
export const {
    UPPERCASE,
    LOWERCASE,
    INTEGER,
    WHITESPACE,
    WORD,
    BOUNDARY,
    DIGIT,
    NOT_WHITESPACE,
    NOT_WORD,
    NOT_DIGIT,
    NOT_BOUNDARY,
    TELEPHONE_MASK,
    EXTENSION_MASK} = PATTERNS;
export default PATTERNS;
