const CONDITIONS = {
  REQUIRED: "REQUIRED",
  EMAIL: "EMAIL",
  NUMBER: "NUMBER",
  INTEGER: "INTEGER",
  DATE: "DATE",
  TIME: "TIME",
  ALPHA: "ALPHA",
  NUMERIC: "NUMERIC",
  SPECIAL: "SPECIAL",
  UPPERCASE: "UPPERCASE",
  LOWERCASE: "LOWERCASE",
  MINIMUM_LENGTH: "MINIMUM_LENGTH",
  MINIMUM_VALUE: "MINIMUM_VALUE",
  MINIMUM_ALPHA: "MINIMUM_ALPHA",
  MINIMUM_NUMERIC: "MINIMUM_NUMERIC",
  MINIMUM_SPECIAL: "MINIMUM_SPECIAL",
  MINIMUM_UPPERCASE: "MINIMUM_UPPERCASE",
  MINIMUM_LOWERCASE: "MINIMUM_LOWERCASE",
  MAXIMUM_LENGTH: "MAXIMUM_LENGTH",
  MAXIMUM_VALUE: "MAXIMUM_VALUE",
  RESTRICT_ALPHA: "RESTRICT_ALPHA",
  RESTRICT_NUMERIC: "RESTRICT_NUMERIC",
  RESTRICT_ALPHANUMERIC: "RESTRICT_ALPHANUMERIC",
  RESTRICT_VALUE: "RESTRICT_VALUE",
  UNAVAILABLE: "UNAVAILABLE"
};
export const {
  REQUIRED, EMAIL, NUMBER, INTEGER, DATE, TIME, ALPHA, NUMERIC, SPECIAL,
  UPPERCASE, LOWERCASE, MINIMUM_LENGTH, MINIMUM_VALUE, MINIMUM_ALPHA,
  MINIMUM_NUMERIC, MINIMUM_SPECIAL, MINIMUM_UPPERCASE, MINIMUM_LOWERCASE,
  MAXIMUM_LENGTH, MAXIMUM_VALUE, RESTRICT_ALPHA, RESTRICT_NUMERIC,
  RESTRICT_ALPHANUMERIC, RESTRICT_VALUE, UNAVAILABLE
} = CONDITIONS;
export default CONDITIONS;
