const TYPES = {
    INFORMATION: 'INFORMATION',
    SUCCESSFUL: 'SUCCESSFUL',
    REDIRECTION: 'REDIRECTION',
    CLIENT_ERROR: 'CLIENT_ERROR',
    SERVER_ERROR: 'SERVER_ERROR',
};
export const {INFORMATION, SUCCESSFUL, REDIRECTION, CLIENT_ERROR, SERVER_ERROR} = TYPES;
export default TYPES;
