export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';
export const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS';
export const LOAD_AUTHORS_SUCCESS = 'LOAD_AUTHORS_SUCCESS';
export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS';
export const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS';
export const DELETE_COURSE_SUCCESS = 'DELETE_COURSE_SUCCESS';
export const LOAD_COURSES_ERROR = 'LOAD_COURSES_ERROR';
export const LOAD_AUTHORS_ERROR = 'LOAD_AUTHORS_ERROR';
export const CREATE_COURSE_ERROR = 'CREATE_COURSE_ERROR';
export const UPDATE_COURSE_ERROR = 'UPDATE_COURSE_ERROR';
export const DELETE_COURSE_ERROR = 'DELETE_COURSE_ERROR';
export const TOGGLE_NAVBAR = 'TOGGLE_NAVBAR';

