export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const TOGGLE_NAVBAR = 'TOGGLE_NAVBAR';
export const CLOSE_NAVBAR = 'CLOSE_NAVBAR';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const UPDATE_LOGIN_FORM = 'UPDATE_LOGIN_FORM';

export const INITIALIZE_REGISTRATION = 'INITIALIZE_REGISTRATION';
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const UPDATE_REGISTRATION_FORM = 'UPDATE_REGISTRATION_FORM';
export const UPDATE_REGISTRATION_FIELD = 'UPDATE_REGISTRATION_FIELD';
export const UPDATE_REGISTRATION_ERRORS = 'UPDATE_REGISTRATION_ERRORS';


export const LOAD_HOME_LINKS = 'LOAD_HOME_LINKS';
export const LOAD_USER_LINKS = 'LOAD_USER_LINKS';

export const LAUNCH_TOAST_MESSAGE = 'LAUNCH_TOAST_MESSAGE';
