import METHODS from '../constants/request/methods';
import CONTENT_TYPE from '../constants/request/headers/contentType';
import X_REQUESTED_WITH from '../constants/request/headers/xRequestedWith';
export default {
    [METHODS.GET]: [X_REQUESTED_WITH.XML_HTTP_REQUEST, CONTENT_TYPE.APPLICATION_X_WWW_FORM_URL_ENCODED],
    [METHODS.POST]: [CONTENT_TYPE.APPLICATION_JSON],
    [METHODS.PUT]: [CONTENT_TYPE.APPLICATION_X_WWW_FORM_URL_ENCODED],
    [METHODS.DELETE]: [X_REQUESTED_WITH.XML_HTTP_REQUEST, CONTENT_TYPE.APPLICATION_X_WWW_FORM_URL_ENCODED]
};
