const HEADER_VALUES = {
    CONTENT_TYPE: 'Content-Type',
    APPLICATION_X_WWW_FORM_URL_ENCODED: 'application/x-www-form-urlencoded',
    APPLICATION_JSON: 'application/json',
};
export const {CONTENT_TYPE, APPLICATION_X_WWW_FORM_URL_ENCODED, APPLICATION_JSON} = HEADER_VALUES;
export default {
    HEADER: CONTENT_TYPE,
    APPLICATION_JSON,
    APPLICATION_X_WWW_FORM_URL_ENCODED
};
