export default {
    TEXT_FIELD: 'TEXT_FIELD',
    TEXT_AREA: 'TEXT_AREA',
    SELECT_FIELD: 'SELECT_FIELD',
    MULTISELECT_FIELD: 'MULTISELECT_FIELD',
    CHECKBOX: 'CHECKBOX',
    AUTO_COMPLETE: 'AUTO_COMPLETE',
    DATE_PICKER: 'DATE_PICKER',
    TIME_PICKER: 'TIME_PICKER',
    MASKED_FIELD: 'MASKED_FIELD',
    PHONE_NUMBER: 'PHONE_NUMBER'
};
