const INPUT_TYPES = {
    TEXT_FIELD: 'TEXT_FIELD',
    TEXT_AREA: 'TEXT_AREA',
    DROPDOWN: 'DROPDOWN',
    CHECKBOX: 'CHECKBOX',
    AUTO_COMPLETE: 'AUTO_COMPLETE',
    DATE_PICKER: 'DATE_PICKER',
    TIME_PICKER: 'TIME_PICKER',
    MASKED_FIELD: 'MASKED_FIELD',
    PHONE_NUMBER: 'PHONE_NUMBER'
};
export const {
    TEXT_FIELD,
    DROPDOWN,
    TEXT_AREA,
    AUTO_COMPLETE,
    DATE_PICKER,
    TIME_PICKER,
    CHECKBOX,
    MASKED_FIELD,
    PHONE_NUMBER} = INPUT_TYPES;
