const INPUT_TYPES = {
    TEXT: 'TEXT',
    DROPDOWN: 'DROPDOWN',
    CHOICE: 'CHOICE',
    AUTO_COMPLETE: 'AUTO_COMPLETE',
    DATE: 'DATE',
    TIME: 'TIME'
};
export const {TEXT, DROPDOWN, CHOICE, AUTO_COMPLETE, DATE, TIME} = INPUT_TYPES;
export default INPUT_TYPES;
