import CONSTRAINTS from '../../validation/constants/constraints'
export default {
    NAME: 'NAME',
    INPUT: 'INPUT',
    REQUIRED: CONSTRAINTS.REQUIRED,
    RESTRICT: CONSTRAINTS.RESTRICT,
    MAXIMUM: CONSTRAINTS.MAXIMUM,
    MINIMUM: CONSTRAINTS.MINIMUM
};
