const STATUS = {
  UNAUTHENTICATED: "UNAUTHENTICATED",
  AUTHENTICATED: "AUTHENTICATED",
  ADMINISTRATOR: "ADMINISTRATOR"
};
export const {UNAUTHENTICATED, AUTHENTICATED, ADMINISTRATOR} = STATUS;
export default STATUS;
