const appointmentActions = {
    UPDATE_APPOINTMENT_TIME: 'UPDATE_APPOINTMENT_TIME',
    UPDATE_APPOINTMENT_DATE: 'UPDATE_APPOINTMENT_DATE',
    UPDATE_APPOINTMENT_DETAILS: 'UPDATE_APPOINTMENT_DETAILS',
    UPDATE_APPOINTMENT_FLEXIBLE: 'UPDATE_APPOINTMENT_FLEXIBLE',
    UPDATE_APPOINTMENT_LOCATION: 'UPDATE_APPOINTMENT_LOCATION',
    UPDATE_APPOINTMENT_CONFIRMATION: 'UPDATE_APPOINTMENT_CONFIRMATION',
    LOAD_APPOINTMENTS: 'LOAD_APPOINTMENTS'
};
export const {
    UPDATE_APPOINTMENT_DATE,
    UPDATE_APPOINTMENT_FLEXIBLE,
    UPDATE_APPOINTMENT_DETAILS,
    UPDATE_APPOINTMENT_TIME,
    UPDATE_APPOINTMENT_LOCATION,
    UPDATE_APPOINTMENT_CONFIRMATION,
    LOAD_APPOINTMENTS
} = appointmentActions;
export default appointmentActions;
