const contactActions = {
    UPDATE_CONTACT_FIRST_NAME: 'UPDATE_CONTACT_FIRST_NAME',
    UPDATE_CONTACT_LAST_NAME: 'UPDATE_CONTACT_LAST_NAME',
    UPDATE_CONTACT_EMAIL_ADDRESS: 'UPDATE_CONTACT_EMAIL_ADDRESS',
    UPDATE_CONTACT_PHONE_NUMBER: 'UPDATE_CONTACT_PHONE_NUMBER',
    UPDATE_CONTACT_EXTENSION: 'UPDATE_CONTACT_EXTENSION',
    SAVE_CONTACT: 'SAVE_CONTACT'
};
export const {
    UPDATE_CONTACT_FIRST_NAME,
    UPDATE_CONTACT_LAST_NAME,
    UPDATE_CONTACT_EMAIL_ADDRESS,
    UPDATE_CONTACT_PHONE_NUMBER,
    UPDATE_CONTACT_EXTENSION,
    SAVE_CONTACT
} = contactActions;
export default contactActions;
