const emailActions = {
    UPDATE_EMAIL_ADDRESS: 'UPDATE_EMAIL_ADDRESS',
    UPDATE_EMAIL_PASSWORD: 'UPDATE_EMAIL_PASSWORD',
    UPDATE_EMAIL_STATUS: 'UPDATE_EMAIL_STATUS'
};
export const {UPDATE_EMAIL_ADDRESS, UPDATE_EMAIL_PASSWORD, UPDATE_EMAIL_STATUS} = emailActions;
export default emailActions;
