const LOCATION_ACTIONS = {
    UPDATE_LOCATION_NAME: 'UPDATE_LOCATION_NAME',
    UPDATE_LOCATION_STREET: 'UPDATE_LOCATION_STREET',
    UPDATE_LOCATION_CITY: 'UPDATE_LOCATION_CITY',
    UPDATE_LOCATION_STATE: 'UPDATE_LOCATION_STATE',
    UPDATE_LOCATION_ZIP: 'UPDATE_LOCATION_ZIP',
    UPDATE_LOCATION_INSTITUTION: 'UPDATE_LOCATION_INSTITUTION',
    UPDATE_LOCATION: 'UPDATE_LOCATION',
    UPDATE_LOCATION_ERROR_INFO: 'UPDATE_LOCATION_ERROR_INFO',
    SAVE_LOCATION: 'SAVE_LOCATION'
};
export const {UPDATE_LOCATION_ERROR_INFO} = LOCATION_ACTIONS;
export default LOCATION_ACTIONS;
