const locationActions = {
    UPDATE_LOCATION_NAME: 'UPDATE_LOCATION_NAME',
    UPDATE_LOCATION_STREET: 'UPDATE_LOCATION_STREET',
    UPDATE_LOCATION_CITY: 'UPDATE_LOCATION_CITY',
    UPDATE_LOCATION_STATE: 'UPDATE_LOCATION_STATE',
    UPDATE_LOCATION_ZIP: 'UPDATE_LOCATION_ZIP',
    UPDATE_LOCATION_INSTITUTION: 'UPDATE_LOCATION_INSTITUTION',
    UPDATE_LOCATION: 'UPDATE_LOCATION',
    SAVE_LOCATION: 'SAVE_LOCATION'
};
export const {
    UPDATE_LOCATION_NAME,
    UPDATE_LOCATION_STREET,
    UPDATE_LOCATION_CITY,
    UPDATE_LOCATION_STATE,
    UPDATE_LOCATION_ZIP,
    UPDATE_LOCATION_INSTITUTION,
    UPDATE_LOCATION,
    SAVE_LOCATION
} = locationActions;
export default locationActions;
